version: "3.8"

services:

  postgres_db:
    container_name: postgres
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - "postgres_db"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres_db:5432/smart_farm_dev
    ports:
      - "4000:4000"